# Generated by Django 6.0.3 on 2026-07-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_videos',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='api.video'),
        ),
    ]
