# Generated by Django 6.0.7 on 2026-07-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assignments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='exams_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='outline',
            field=models.JSONField(blank=True, default=list, help_text='List of outline topics'),
        ),
        migrations.AddField(
            model_name='course',
            name='quizzes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='roadmap',
            field=models.JSONField(blank=True, default=list, help_text='List of roadmap milestones'),
        ),
    ]
