# Generated by Django 6.0.3 on 2026-08-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_attachments/'),
        ),
    ]
